config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  root to: 'doctors#index'

  get     'login',  to: 'sessions#new'
  delete  'logout', to: 'sessions#destroy'
  post    'login',  to: 'sessions#create'

  post 'patient', to: 'patients#create'
  get 'new_patient', to: 'patients#new'
  get  'profile', to: 'patients#profile'

  get  'my_patients', to: 'doctors#my_patients'
  get  'my_patient',  to: 'patients#show'
  post  'update_patient',  to: 'patients#update'
  post  'update_comment',  to: 'heart_rates#update_comment'
  post  'pulse_comment',  to: 'pulses#comment'

  resources :doctors, only: [:index, :show]
  resources :pulses, only: [:index, :show]
  resources :ecg, only: [:index, :show]
  resources :medical_files

  get 'download_file', to: "medical_files#download"

  namespace 'api' do
    # post 'signup', to: 'users#create'
    post 'login', to: 'authentication#login'
    # post 'logout', to: 'sessions#destroy'

    get 'patient/info', to: 'patients#info'
    post 'medical_file', to: 'medical_files#create'

    post 'save_pulse', to: 'pulse#create'
    post 'ecg', to: 'ecg#create'
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_secure_password

  mount_uploader :avatar, AvatarUploader

  has_many :patients
end

app/models/heart_rate.rb
class HeartRate < ApplicationRecord
  mount_uploader :file, ImageUploader

  belongs_to :patient
end

app/models/medical_datum.rb
class MedicalDatum < ApplicationRecord
  belongs_to :patient
end

app/models/medical_file.rb
class MedicalFile < ApplicationRecord
  mount_uploader :file, ImageUploader

  belongs_to :patient
end

app/models/patient.rb
  class Patient < ApplicationRecord
    has_secure_password

    mount_uploader :avatar, AvatarUploader

    has_many :heart_rates
    has_many :pulse_oximeters

    belongs_to :doctor
  end

app/models/pulse_oximeter.rb
class PulseOximeter < ApplicationRecord
  belongs_to :patient
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  before_action :current_user

  def current_user
    if session[:patient_id]
      @current_user ||= Patient.find(session[:patient_id])
    elsif session[:doctor_id]
      @current_user ||= Doctor.find(session[:doctor_id])
    else
      # @current_user ||= Patient.find(session[:patient_id])
      @current_user = nil
    end
  end

  # def current_doctor
  #   if session[:doctor_id]

  #   else
  #     @current_user = nil
  #   end
  # end

  def _patient
    if @current_user.class == Doctor
      @current_user.patients.find(params[:patient])
    else
      @current_user
    end
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  # skip_before_action :current_user
  # before_action :current_doctor

  def index
    @doctors = Doctor.all
  end

  def new_patient
    @user = Patient.new
  end

  def my_patients
    @patients = @current_user.patients
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id # to automatically login a user that signed up
      flash[:notice] = "You are registered."
      redirect_to root_path
    else
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:login, :password)
  end
end

app/controllers/ecg_controller.rb
class EcgController < ApplicationController
  # before_action :current_doctor

  def index
    @ecg_readings = _patient.heart_rates.where.not(value: [])
  end

  def show
    @ecg_reading = HeartRate.find(params[:id])
    @patient = @ecg_reading.patient

    @ecg_value = @ecg_reading.value.map {|value| value.to_i}
    # @ecg_value = @ecg_reading.file
  end
end

app/controllers/heart_rates_controller.rb
class HeartRatesController < ApplicationController
  def update_comment
    @ecg_reading = HeartRate.find(params[:id])
    @ecg_reading.update(comment: params[:comment])
  end
end

app/controllers/medical_files_controller.rb
class MedicalFilesController < ApplicationController
  # before_action :current_doctor

  def index
    @files = _patient.heart_rates.where.not(file: nil)
  end

  def show
    @file = HeartRate.find(params[:id])

    if @file.file.content_type == "application/pdf"
      send_file(@file.file.path)
    end
  end

  def create
    if _patient.heart_rates.create(file_params)
      redirect_to medical_files_path(patient: _patient.id)
    else
      render :new
    end
  end

  def download
    file = HeartRate.find(params[:id])
    send_file(file.file.path)
  end

  def file_params
    params.require(:medical_file).permit(:file)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  # skip_before_action :current_user, only: [:show]
  # before_action :current_doctor, only: [:show]
  def new; end

  def profile
    @patient = Patient.first
    @my_doctor = @patient.doctor
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def create
    @user = @current_user.patients.new(patient_params)

    if @user.save
      redirect_to my_patients_path
    else
      render :new
    end
  end

  def update
    @patient = Patient.find(params[:id])
    @patient.update(patient_params)
    redirect_to my_patient_path(id: @patient.id)
  end

  def patient_params
    params.permit(:id, :last_name, :name, :patronymic, :email, :dob, :address, :phone_number, :blood_type, :allergy, :password)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @patient = Patient.first
  end

  def show
    @m_d = MedicalDatum.find(params[:id])
    @patient = @m_d.patient
    @type = 'ecg'
  end

  def write
    # {"lat"=>"37.4219983", "lon"=>"-122.084", "number"=>"5", "dir"=>"1", "controller"=>"medical_datums", "action"=>"write"}
    patient = Patient.first
    # med_data = patient.medical_datums.create(data_type: params['type'], basic_data: params)
    render json: {}
  end
end

app/controllers/pulses_controller.rb
class PulsesController < ApplicationController
  # before_action :current_doctor

  def index
    @pulses = _patient.pulse_oximeters
  end

  def show
    @patient = _patient
    @pulse = _patient.pulse_oximeters.find(params[:id])
    @array = @pulse.value.map {|value| value.to_i }
  end

  def comment
    @pulse = PulseOximeter.find(params[:id])
    @pulse.update(comment: params[:comment])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = Patient.where(phone_number: params[:phone_number]).first || Doctor.where(phone_number: params[:phone_number]).first

    if user && user.authenticate(params[:password])
      _new_session(user)
    else
      redirect_to root_url
    end
  end

  def destroy
    session[:patient_id] = nil
    session[:doctor_id] = nil
    redirect_to root_url
  end

  private

  def _new_session(user)
    if user.class == Doctor
      session[:doctor_id] = user.id
      redirect_to my_patients_url
    else
      session[:patient_id] = user.id
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(path)
    return 'active' if current_page?(path)
  end

  def is_doctor?
    @current_user.class == Doctor
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_root_page.html.erb
<body>
  <form class="vldform vldauth" action="login" method="POST">
    <h1>Вход</h1>
    <input class="vldform__textbox" type="text" name="phone_number" placeholder="Логин" required>
    <input class="vldform__textbox" type="password" name="password" id="" placeholder="Пароль" required>
    <%# <a class="vldform__recoverypassword" href="#" onclick="showrecoveryform()">Forgot password?</a> %>
    <input class="vldform__button" type="submit" value="Войти">
  </form>
</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
function showregform(){
    document.title = "Регистрация";
    document.querySelector(".vldauth").style.display = "none";
    document.querySelector(".vldreg").style.display = "flex";
}

function showauthform(){
    document.title = "Вход";
    document.querySelector(".vldauth").style.display = "flex";
    document.querySelector(".vldreg").style.display = "none";
    document.querySelector(".vldrecpass").style.display = "none";
}
</script>

<style>
@import url('https://fonts.googleapis.com/css?family=Nunito+Sans');


body {
  display: flex;
  justify-content: center;
}

.vldform {
    box-sizing: border-box;
    margin-top: 100px;
    width: 375px;
    display: flex;
    flex-direction: column;
    padding: 35px 55px;
    font-family: "Nunito Sans";
    animation: a .5s;
    animation-fill-mode: forwards;
    border: #d4d4d4 1px solid;
    border-radius: 10px;
    box-shadow: 0 2px 6px 0 hsla(0, 0%, 0%, 0.2);
}

.vldform a {
    text-decoration: none;
}

.vldform h1 {
    font-size: 40px;
    color: #552FAB;
    margin: 0px 0px 26px 0px;
}

.vldform__textbox {
    border: 0;
    outline: 0;
    border-bottom: 2px #512DA8 solid;
    font-size: 18px;
    margin-top: 36px;
    padding-bottom: 9px;
    font-family: "Nunito Sans";
}

.vldform__textbox[type="password"]::after {
    content: " ";
    display: block;
    width: 10px;
    height: 10px;
    background-color: rebeccapurple;

}

.vldform__recoverypassword{
    align-self: flex-end;
    margin: 10px 0px;
    font-size: 16px;
    color: #2E67A9;
}

.vldform__button {
    margin-top: 42px;
    height: 50px;
    border: 0;
    color: #fff;
    border-radius: 10px;
    background-image: linear-gradient(#512DA8, #673AB7);
    font-size: 22px;
    font-weight: 600;
    font-family: "Nunito Sans";
    cursor: pointer;
}

.vldform__signup {
    align-self: center;
    margin-top: 50px;
    margin-bottom: 0px;
}

.vldform__signup a {
    color: #6538B5;
    font-weight: 600;
    margin-left: 4px;
}

.vldreg {
    display: none;
}

.vldrecpass {
    display: none;
}

@keyframes a {
    0% {
        opacity: 0;
        transform: translateY(-5px)
    }

    to {
        opacity: 1;
        transform: translateY(5px)
    }
}

@media (max-width: 400px) {
    .vldform {
        width: 350px;
        padding: 20px 40px;
    }

}

@media (max-width: 360px) {
    .vldform {
        width: 305px;
        padding: 20px 35px;
    }

    .vldform__signup {
        text-align: center;
    }

    .vldform__signup a {
        margin-left: 14px;
    }
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MedicalCenter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <% if @current_user %>
      <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application' %>

      <div class="wrapper ">
        <%= render 'partials/sidebar' %>
        <div class="main-panel">
          <%= yield %>
        </div>
      </div>
    <% else %>
      <%= render 'layouts/root_page' %>
    <% end %>
  </body>
</html>

app/views/partials/_sidebar.html.erb
<div class="sidebar" data-color="purple" data-background-color="white" data-image="<%= image_path('sidebar.jpg')%>">
  <div class="logo">
    <a href="http://www.creative-tim.com" class="simple-text logo-normal">
      Medical Center
    </a>
  </div>
  <div class="sidebar-wrapper">
    <ul class="nav">
      <% if @current_user.class == Doctor %>
        <li class="nav-item <%= active_class(new_patient_path)%>">
          <a class="nav-link" href="<%= new_patient_path %>">
            <i class="material-icons">person_add</i>
            <p>Добавить пациента</p>
          </a>
        </li>
        <li class="nav-item <%= active_class(my_patients_path)%>">
          <a class="nav-link" href="<%= my_patients_path %>">
            <i class="material-icons">group</i>
            <p>Мои пациенты</p>
          </a>
        </li>
      <% else %>
      <li class="nav-item <%= active_class(doctors_path)%>">
        <a class="nav-link" href="<%= doctors_path %>">
          <i class="material-icons">group</i>
          <p>Врачи</p>
        </a>
      </li>
      <li class="nav-item <%= active_class(profile_path)%>">
        <a class="nav-link" href="<%= profile_path %>">
          <i class="material-icons">person</i>
          <p>Мой Профиль</p>
        </a>
      </li>
      <li class="nav-item <%= active_class(pulses_path)%>">
        <a class="nav-link" href="<%= pulses_path %>">
          <i class="material-icons">timeline</i>
          <p>Пульс</p>
        </a>
      </li>
      <li class="nav-item <%= active_class(ecg_index_path)%>">
        <a class="nav-link" href="<%= ecg_index_path %>">
          <i class="material-icons">show_chart</i>
          <p>ЭКГ</p>
        </a>
      </li>
      <li class="nav-item <%= active_class(medical_files_path)%>">
        <a class="nav-link" href="<%= medical_files_path %>">
          <i class="material-icons">library_books</i>
          <p>Снимки</p>
        </a>
      </li>
      <% end %>
      <li class="nav-item active-pro">
        <a class="nav-link" href="/logout" data-method="delete">
          <i class="material-icons">exit_to_app</i>
          <p>Exit</p>
        </a>
      </li>
    </ul>
  </div>
</div>