config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  root to: 'doctors#index'

  get     'login',  to: 'sessions#new'
  delete  'logout', to: 'sessions#destroy'
  post    'login',  to: 'sessions#create'

  post 'patient', to: 'patients#create'
  get 'new_patient', to: 'patients#new'
  get  'profile', to: 'patients#profile'

  get  'my_patients', to: 'doctors#my_patients'
  get  'my_patient',  to: 'patients#show'
  post  'update_patient',  to: 'patients#update'
  post  'update_comment',  to: 'heart_rates#update_comment'
  post  'pulse_comment',  to: 'pulses#comment'

  resources :doctors, only: [:index, :show]
  resources :pulses, only: [:index, :show]
  resources :ecg, only: [:index, :show]
  resources :medical_files

  get 'download_file', to: "medical_files#download"

  namespace 'api' do
    # post 'signup', to: 'users#create'
    post 'login', to: 'authentication#login'
    # post 'logout', to: 'sessions#destroy'

    get 'patient/info', to: 'patients#info'
    post 'medical_file', to: 'medical_files#create'

    post 'save_pulse', to: 'pulse#create'
    post 'ecg', to: 'ecg#create'
  end
end

app/models/patient.rb
  class Patient < ApplicationRecord
    has_secure_password

    mount_uploader :avatar, AvatarUploader

    has_many :heart_rates
    has_many :pulse_oximeters

    belongs_to :doctor
  end

app/controllers/api/patients_controller.rb
class Api::PatientsController < Api::BaseController
  # before_action :find_patient, only: %i[info]

  # # GET /users
  # def index
  #   @users = Patient.all
  #   render json: @users, status: :ok
  # end

  # GET /users/{username}
  def info
    render json: @current_user, status: :ok
  end

  # POST /users
  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     render json: @user, status: :created
  #   else
  #     render json: { errors: @user.errors.full_messages },
  #            status: :unprocessable_entity
  #   end
  # end

  # # PUT /users/{username}
  # def update
  #   unless @user.update(user_params)
  #     render json: { errors: @user.errors.full_messages },
  #            status: :unprocessable_entity
  #   end
  # end

  # private

  # def user_params
  #   params.permit(
  #     :avatar, :name, :username, :email, :password, :password_confirmation
  #   )
  # end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  # skip_before_action :current_user, only: [:show]
  # before_action :current_doctor, only: [:show]
  def new; end

  def profile
    @patient = Patient.first
    @my_doctor = @patient.doctor
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def create
    @user = @current_user.patients.new(patient_params)

    if @user.save
      redirect_to my_patients_path
    else
      render :new
    end
  end

  def update
    @patient = Patient.find(params[:id])
    @patient.update(patient_params)
    redirect_to my_patient_path(id: @patient.id)
  end

  def patient_params
    params.permit(:id, :last_name, :name, :patronymic, :email, :dob, :address, :phone_number, :blood_type, :allergy, :password)
  end
end

app/views/patients/new.html.erb
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
  <div class="container-fluid">
    <div class="navbar-wrapper">
      <a class="navbar-brand" href="#pablo">Пользовательский профиль</a>
    </div>
  </div>
</nav>
<!-- End Navbar -->
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">Добавить пациента</h4>
          </div>
          <div class="card-body">
            <form action="patient" method="post" >
              <div class="row">
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">ID</label>
                    <input type="number" class="form-control" name="id">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Пароль</label>
                    <input type="password" class="form-control" name="password">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Фамилия</label>
                    <input type="text" class="form-control" name="last_name">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Имя</label>
                    <input type="text" class="form-control" name="name">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Отчество</label>
                    <input type="text" class="form-control" name="patronymic">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Email</label>
                    <input type="email" class="form-control" name="email">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Дата рождения</label>
                    <input type="text" class="form-control" name="dob">
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Адрес</label>
                    <input type="text" class="form-control" name="address">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Номер телефона</label>
                    <input type="text" class="form-control" name="phone_number">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Группа крови</label>
                    <input type="text" class="form-control" name="blood_type">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Аллергия</label>
                    <input type="text" class="form-control" name="allergy">
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-primary pull-right">Создать</button>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/patients/profile.html.erb
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
  <div class="container-fluid">
    <div class="navbar-wrapper">
      <a class="navbar-brand" href="#pablo">Пользовательский профиль</a>
    </div>
  </div>
</nav>
<!-- End Navbar -->
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title"><%= @patient.last_name %> <%= @patient.name %> <%= @patient.patronymic %></h4>
          </div>
          <div class="card-body">
            <form action="patient" method="post" >
              <div class="row">
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Фамилия</label>
                    <input type="text" class="form-control" name="last_name" value="<%= @patient.last_name %>">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Имя</label>
                    <input type="text" class="form-control" name="name" value="<%= @patient.name %>">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Отчество</label>
                    <input type="text" class="form-control" name="patronymic" value="<%= @patient.patronymic %>">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Email</label>
                    <input type="email" class="form-control" name="email" value="<%= @patient.email %>">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Дата рождения</label>
                    <input type="text" class="form-control" name="dob" value="<%= @patient.dob %>">
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Адрес</label>
                    <input type="text" class="form-control" name="address" value="<%= @patient.address %>">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Номер телефона</label>
                    <input type="text" class="form-control" name="phone_number" value="<%= @patient.phone_number %>">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Группа крови</label>
                    <input type="text" class="form-control" name="blood_type" value="<%= @patient.blood_type %>">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Аллергия</label>
                    <input type="text" class="form-control" name="allergy" value="<%= @patient.allergy %>">
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-primary pull-right">Обновить</button>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card card-profile">
          <div class="card-avatar">
            <%= image_tag @patient.avatar_url, class: 'rounded-circle img-fluid'%>
          </div>
          <div class="card-body">
            <h4 class="card-title">Мой лечащий врач</h4>
            <h3 class="card-category text-gray"><%= @my_doctor.last_name %> <%= @my_doctor.name %> <%= @my_doctor.patronymic %></h3>
            <h6 class="card-category text-gray"><%= @my_doctor.email %></h6>
            <h6 class="card-category text-gray"><%= @my_doctor.phone_number %></h6>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/patients/profile_old.html.erb
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
  <div class="container-fluid">
    <div class="navbar-wrapper">
      <a class="navbar-brand" href="#pablo">Пользовательский профиль</a>
    </div>
  </div>
</nav>
<!-- End Navbar -->
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title"><%= @patient.last_name %> <%= @patient.name %> <%= @patient.patronymic %></h4>
          </div>
          <div class="card-body">
            <form action="patient" method="post" >
              <div class="row">
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Фамилия</label>
                    <input type="text" class="form-control" name="last_name" value="<%= @patient.last_name %>">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Имя</label>
                    <input type="text" class="form-control" name="name" value="<%= @patient.name %>">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Отчество</label>
                    <input type="text" class="form-control" name="patronymic" value="<%= @patient.patronymic %>">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Email</label>
                    <input type="email" class="form-control" name="email" value="<%= @patient.email %>">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Дата рождения</label>
                    <input type="text" class="form-control" name="dob" value="<%= @patient.dob %>">
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Адрес</label>
                    <input type="text" class="form-control" name="address" value="<%= @patient.address %>">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Номер телефона</label>
                    <input type="text" class="form-control" name="phone_number" value="<%= @patient.phone_number %>">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Группа крови</label>
                    <input type="text" class="form-control" name="blood_type" value="<%= @patient.blood_type %>">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Аллергия</label>
                    <input type="text" class="form-control" name="allergy" value="<%= @patient.allergy %>">
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-primary pull-right">Обновить</button>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card card-profile">
          <div class="card-avatar">
            <%= image_tag @patient.avatar_url, class: 'rounded-circle img-fluid'%>
          </div>
          <div class="card-body">
            <h4 class="card-title">Мой лечащий врач</h4>
            <h3 class="card-category text-gray"><%= @my_doctor.last_name %> <%= @my_doctor.name %> <%= @my_doctor.patronymic %></h3>
            <h6 class="card-category text-gray"><%= @my_doctor.email %></h6>
            <h6 class="card-category text-gray"><%= @my_doctor.phone_number %></h6>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/patients/show.html.erb
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
  <div class="container-fluid">
    <div class="navbar-wrapper">
      <a class="navbar-brand" href="#pablo">Пользовательский профиль</a>
    </div>
  </div>
</nav>
<!-- End Navbar -->
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title"><%= @patient.last_name %> <%= @patient.name %> <%= @patient.patronymic %></h4>
          </div>
          <div class="card-body">
            <form action="patient" method="post" >
              <div class="row">
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Фамилия</label>
                    <input type="text" class="form-control" name="last_name" value="<%= @patient.last_name %>">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Имя</label>
                    <input type="text" class="form-control" name="name" value="<%= @patient.name %>">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Отчество</label>
                    <input type="text" class="form-control" name="patronymic" value="<%= @patient.patronymic %>">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Email</label>
                    <input type="email" class="form-control" name="email" value="<%= @patient.email %>">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Дата рождения</label>
                    <input type="text" class="form-control" name="dob" value="<%= @patient.dob %>">
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Адрес</label>
                    <input type="text" class="form-control" name="address" value="<%= @patient.address %>">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Номер телефона</label>
                    <input type="text" class="form-control" name="phone_number" value="<%= @patient.phone_number %>">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Группа крови</label>
                    <input type="text" class="form-control" name="blood_type" value="<%= @patient.blood_type %>">
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <label class="bmd-label-floating">Аллергия</label>
                    <input type="text" class="form-control" name="allergy" value="<%= @patient.allergy %>">
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-primary pull-right">Обновить</button>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card card-profile">
          <div class="card-body">
            <a href="<%= ecg_index_path %>" class="btn btn-primary btn-round">ЭКГ</a>
            <a href="<%= pulses_path %>" class="btn btn-primary btn-round">Пульс</a>
            <a href="<%= medical_files_path %>" class="btn btn-primary btn-round">Файлы</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>