config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  root to: 'doctors#index'

  get     'login',  to: 'sessions#new'
  delete  'logout', to: 'sessions#destroy'
  post    'login',  to: 'sessions#create'

  post 'patient', to: 'patients#create'
  get 'new_patient', to: 'patients#new'
  get  'profile', to: 'patients#profile'

  get  'my_patients', to: 'doctors#my_patients'
  get  'my_patient',  to: 'patients#show'
  post  'update_patient',  to: 'patients#update'
  post  'update_comment',  to: 'heart_rates#update_comment'
  post  'pulse_comment',  to: 'pulses#comment'

  resources :doctors, only: [:index, :show]
  resources :pulses, only: [:index, :show]
  resources :ecg, only: [:index, :show]
  resources :medical_files

  get 'download_file', to: "medical_files#download"

  namespace 'api' do
    # post 'signup', to: 'users#create'
    post 'login', to: 'authentication#login'
    # post 'logout', to: 'sessions#destroy'

    get 'patient/info', to: 'patients#info'
    post 'medical_file', to: 'medical_files#create'

    post 'save_pulse', to: 'pulse#create'
    post 'ecg', to: 'ecg#create'
  end
end

app/models/medical_file.rb
class MedicalFile < ApplicationRecord
  mount_uploader :file, ImageUploader

  belongs_to :patient
end

app/controllers/api/medical_files_controller.rb
class Api::MedicalFilesController < Api::BaseController
   #before_action :find_patient, only: %i[info]
  skip_before_action :authorize_request

  def create
    @patient = Patient.first
    if @patient.heart_rates.create(file_params)
      render status: 200, json: {
        message: "Фаил успешно сохранен"
      }.to_json
    else
      render json: { error: 'Фаил не был сохранен' }, status: :unauthorized
    end
  end

  private

  def file_params
    params.permit(:file, :title)
  end
end

app/controllers/medical_files_controller.rb
class MedicalFilesController < ApplicationController
  # before_action :current_doctor

  def index
    @files = _patient.heart_rates.where.not(file: nil)
  end

  def show
    @file = HeartRate.find(params[:id])

    if @file.file.content_type == "application/pdf"
      send_file(@file.file.path)
    end
  end

  def create
    if _patient.heart_rates.create(file_params)
      redirect_to medical_files_path(patient: _patient.id)
    else
      render :new
    end
  end

  def download
    file = HeartRate.find(params[:id])
    send_file(file.file.path)
  end

  def file_params
    params.require(:medical_file).permit(:file)
  end
end

app/views/medical_files/form.html.erb
 <%= form_for HeartRate.new do |f| %>
                  <div class="input-group custom-input-group test-file-input">
                    <div class="form-group form-file-upload form-file-multiple">
                      <input type="file" multiple="" class="inputFileHidden">
                      <div class="input-group">
                        <span class="input-group-btn">
                            <%= f.text_field(:title, class: 'form-control') %>
                            <%= f.file_field(:file, class: 'form-control input-file', id: "individual-avatar") %>
                            <label tabindex="0" for="individual-avatar" class="input-file-trigger" id="individual-file-trigger">Upload avatar</label>
                            <button type="button" class="btn btn-fab btn-round btn-primary">
                                <i class="material-icons">attach_file</i>
                            </button>
                            <%= f.submit %>
                        </span>
                      </div>
                    </div>
                  </div>
                <% end %>

app/views/medical_files/index.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
  <div class="container-fluid">
    <div class="navbar-wrapper">
      <a class="navbar-brand">Снимки</a>
    </div>
  </div>
</nav>
<!-- End Navbar -->
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-plain">
          <div class="card-header card-header-primary">
            <h4 class="card-title mt-0"> Снимки и Файлы</h4>
            <% if @current_user.class == Doctor %>
              <button class="btn btn-round" id="myBtn" data-toggle="modal" data-target="#loginModal" style="margin-left: 40%;">
                  Загрузить снимок
              </button>
            <% end %>
            <div id="myModal" class="modal">
              <div class="modal-content">
                <span class="close">&times;</span>
                <%= form_for HeartRate.new, as: :medical_file, url: medical_files_path do |f| %>
                  <div class="input-group custom-input-group test-file-input">
                    <div class="form-group form-file-upload form-file-multiple">
                      <input type="file" multiple="" class="inputFileHidden">
                      <div class="input-group">
                        <span class="input-group-btn">
                            <%= hidden_field_tag 'patient', params[:patient]  %>
                            <%= f.file_field(:file, class: 'form-control input-file', id: "individual-avatar") %>
                            <label tabindex="0" for="individual-avatar" class="input-file-trigger" id="individual-file-trigger">Upload avatar</label>
                            <button type="button" class="btn btn-fab btn-round btn-primary">
                                <i class="material-icons">attach_file</i>
                            </button>
                            <%= f.submit %>
                        </span>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead class="">
                  <th>
                    ID
                  </th>
                  <th>
                    Тип файла
                  </th>
                  <th>
                    Дата
                  </th>
                </thead>
                <tbody>
                  <% @files.each do |file| %>
                  <tr class="table-row" data-href="<%= medical_file_path(file) %>">
                    <td>
                      <%= file.id %>
                    </td>
                    <td>
                      <% if file.file.content_type %>
                      <%= file.file.content_type.split('/').last %>
                      <% end %>
                    </td>
                    <td>
                      <%= file.created_at %>
                    </td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function($) {
    $(".table-row").click(function() {
        window.document.location = $(this).data("href");
    });
});

// Get the modal
var modal = document.getElementById("myModal");

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on the button, open the modal
btn.onclick = function() {
  modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>


<style>
/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: rgb(0,0,0); /* Fallback color */
  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content/Box */
.modal-content {
  background-color: #fefefe;
  margin: 15% auto; /* 15% from the top and centered */
  padding: 20px;
  border: 1px solid #888;
  width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button */
.close {
  color: #aaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}

.close:hover,
.close:focus {
  color: black;
  text-decoration: none;
  cursor: pointer;
}

.left-check-input {
  left: 17px;
  margin-bottom: 5px;
}

.horizontal-line {
  width: 310px;
  height: 1px;
  left: 565px;

  background: #ECECEC;
}

.test-file-input {
    position: relative;
    margin-bottom: 5px;
}

.input-file {
  position: absolute;
  top: 0; left: 56px;
  width: 235px;
  opacity: 0;
  padding: 14px 0;
  cursor: pointer;
}

.input-file-trigger {
  padding-top: 10px;
  width: 255px;
  text-align: left;
  border-bottom: 1px solid #ced4da;
  padding-bottom: 5px;
}
</style>

app/views/medical_files/show.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
  <div class="container-fluid">
    <div class="navbar-wrapper">
      <a class="navbar-brand">DICOM</a>
    </div>
  </div>
</nav>
<!-- End Navbar -->
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-plain">
          <% if @current_user.class == Doctor %>
            <div class="card-header card-header-primary">
              <%= link_to 'Скачать', download_file_path(id: @file), class: "btn btn-round", style: "margin-left: 40%;" %>
            </div>
          <% end %>
          <div class="card-body">
            <div class="table-responsive">
              <div id="dwv">
                <div class="layerContainer">
                    <canvas class="imageLayer"></canvas>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<% if is_doctor? %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <form action="<%= update_comment_path %>" method="post" >
              <div class="container-fluid">
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label>Комментарий</label>
                      <div class="form-group">
                        <textarea class="form-control" rows="5" name='comment' value="<%= @file.comment %>"></textarea>
                        <input type="hidden" name="id" value="<%= @file.id %>" />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-primary pull-right">Изменить</button>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <form action="patient" method="post" >
              <div class="container-fluid">
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label>Комментарий</label>
                      <div class="form-group">
                        <%# <label class="bmd-label-floating"> </label> %>
                        <h4><%= @file.comment %></h4>
                        <%# <textarea class="form-control" rows="5" value=""></textarea> %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
  </div>


<script>
  // base function to get elements
  dwv.gui.getElement = dwv.gui.base.getElement;
  dwv.gui.displayProgress = function (percent) {};

  // create the dwv app
  var app = new dwv.App();
  // initialise with the id of the container div
  app.init({
      "containerDivId": "dwv"
  });
  // load dicom data
  app.loadURLs(["<%= @file.file_url %>"]);
</script>