config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  root to: 'doctors#index'

  get     'login',  to: 'sessions#new'
  delete  'logout', to: 'sessions#destroy'
  post    'login',  to: 'sessions#create'

  post 'patient', to: 'patients#create'
  get 'new_patient', to: 'patients#new'
  get  'profile', to: 'patients#profile'

  get  'my_patients', to: 'doctors#my_patients'
  get  'my_patient',  to: 'patients#show'
  post  'update_patient',  to: 'patients#update'
  post  'update_comment',  to: 'heart_rates#update_comment'
  post  'pulse_comment',  to: 'pulses#comment'

  resources :doctors, only: [:index, :show]
  resources :pulses, only: [:index, :show]
  resources :ecg, only: [:index, :show]
  resources :medical_files

  get 'download_file', to: "medical_files#download"

  namespace 'api' do
    # post 'signup', to: 'users#create'
    post 'login', to: 'authentication#login'
    # post 'logout', to: 'sessions#destroy'

    get 'patient/info', to: 'patients#info'
    post 'medical_file', to: 'medical_files#create'

    post 'save_pulse', to: 'pulse#create'
    post 'ecg', to: 'ecg#create'
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_secure_password

  mount_uploader :avatar, AvatarUploader

  has_many :patients
end

app/models/heart_rate.rb
class HeartRate < ApplicationRecord
  mount_uploader :file, ImageUploader

  belongs_to :patient
end

app/models/medical_datum.rb
class MedicalDatum < ApplicationRecord
  belongs_to :patient
end

app/models/medical_file.rb
class MedicalFile < ApplicationRecord
  mount_uploader :file, ImageUploader

  belongs_to :patient
end

app/models/patient.rb
  class Patient < ApplicationRecord
    has_secure_password

    mount_uploader :avatar, AvatarUploader

    has_many :heart_rates
    has_many :pulse_oximeters

    belongs_to :doctor
  end

app/models/pulse_oximeter.rb
class PulseOximeter < ApplicationRecord
  belongs_to :patient
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  before_action :current_user

  def current_user
    if session[:patient_id]
      @current_user ||= Patient.find(session[:patient_id])
    elsif session[:doctor_id]
      @current_user ||= Doctor.find(session[:doctor_id])
    else
      # @current_user ||= Patient.find(session[:patient_id])
      @current_user = nil
    end
  end

  # def current_doctor
  #   if session[:doctor_id]

  #   else
  #     @current_user = nil
  #   end
  # end

  def _patient
    if @current_user.class == Doctor
      @current_user.patients.find(params[:patient])
    else
      @current_user
    end
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  # skip_before_action :current_user
  # before_action :current_doctor

  def index
    @doctors = Doctor.all
  end

  def new_patient
    @user = Patient.new
  end

  def my_patients
    @patients = @current_user.patients
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id # to automatically login a user that signed up
      flash[:notice] = "You are registered."
      redirect_to root_path
    else
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:login, :password)
  end
end

app/controllers/ecg_controller.rb
class EcgController < ApplicationController
  # before_action :current_doctor

  def index
    @ecg_readings = _patient.heart_rates.where.not(value: [])
  end

  def show
    @ecg_reading = HeartRate.find(params[:id])
    @patient = @ecg_reading.patient

    @ecg_value = @ecg_reading.value.map {|value| value.to_i}
    # @ecg_value = @ecg_reading.file
  end
end

app/controllers/heart_rates_controller.rb
class HeartRatesController < ApplicationController
  def update_comment
    @ecg_reading = HeartRate.find(params[:id])
    @ecg_reading.update(comment: params[:comment])
  end
end

app/controllers/medical_datums_controller.rb
class MedicalDatumsController < ApplicationController

  def index
    @patient = Patient.first
  end

  def show
    @m_d = MedicalDatum.find(params[:id])
    @patient = @m_d.patient
    @type = 'file'
  end

  def write
    # {"lat"=>"37.4219983", "lon"=>"-122.084", "number"=>"5", "dir"=>"1", "controller"=>"medical_datums", "action"=>"write"}
    patient = Patient.first
    # med_data = patient.medical_datums.create(data_type: params['type'], basic_data: params)
    render json: {}
  end
end

app/controllers/medical_files_controller.rb
class MedicalFilesController < ApplicationController
  # before_action :current_doctor

  def index
    @files = _patient.heart_rates.where.not(file: nil)
  end

  def show
    @file = HeartRate.find(params[:id])

    if @file.file.content_type == "application/pdf"
      send_file(@file.file.path)
    end
  end

  def create
    if _patient.heart_rates.create(file_params)
      redirect_to medical_files_path(patient: _patient.id)
    else
      render :new
    end
  end

  def download
    file = HeartRate.find(params[:id])
    send_file(file.file.path)
  end

  def file_params
    params.require(:medical_file).permit(:file)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  # skip_before_action :current_user, only: [:show]
  # before_action :current_doctor, only: [:show]
  def new; end

  def profile
    @patient = Patient.first
    @my_doctor = @patient.doctor
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def create
    @user = @current_user.patients.new(patient_params)

    if @user.save
      redirect_to my_patients_path
    else
      render :new
    end
  end

  def update
    @patient = Patient.find(params[:id])
    @patient.update(patient_params)
    redirect_to my_patient_path(id: @patient.id)
  end

  def patient_params
    params.permit(:id, :last_name, :name, :patronymic, :email, :dob, :address, :phone_number, :blood_type, :allergy, :password)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @patient = Patient.first
  end

  def show
    @m_d = MedicalDatum.find(params[:id])
    @patient = @m_d.patient
    @type = 'ecg'
  end

  def write
    # {"lat"=>"37.4219983", "lon"=>"-122.084", "number"=>"5", "dir"=>"1", "controller"=>"medical_datums", "action"=>"write"}
    patient = Patient.first
    # med_data = patient.medical_datums.create(data_type: params['type'], basic_data: params)
    render json: {}
  end
end

app/controllers/pulses_controller.rb
class PulsesController < ApplicationController
  # before_action :current_doctor

  def index
    @pulses = _patient.pulse_oximeters
  end

  def show
    @patient = _patient
    @pulse = _patient.pulse_oximeters.find(params[:id])
    @array = @pulse.value.map {|value| value.to_i }
  end

  def comment
    @pulse = PulseOximeter.find(params[:id])
    @pulse.update(comment: params[:comment])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = Patient.where(phone_number: params[:phone_number]).first || Doctor.where(phone_number: params[:phone_number]).first

    if user && user.authenticate(params[:password])
      _new_session(user)
    else
      redirect_to root_url
    end
  end

  def destroy
    session[:patient_id] = nil
    session[:doctor_id] = nil
    redirect_to root_url
  end

  private

  def _new_session(user)
    if user.class == Doctor
      session[:doctor_id] = user.id
      redirect_to my_patients_url
    else
      session[:patient_id] = user.id
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(path)
    return 'active' if current_page?(path)
  end

  def is_doctor?
    @current_user.class == Doctor
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/pulses/index.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
  <div class="container-fluid">
    <div class="navbar-wrapper">
      <a class="navbar-brand">Пульс</a>
    </div>
  </div>
</nav>
<!-- End Navbar -->
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-plain">
          <div class="card-header card-header-primary">
            <h4 class="card-title mt-0"> Показания пульса</h4>
            <p class="card-category"> * </p>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead class="">
                  <th>
                    ID
                  </th>
                  <th>
                    Дата
                  </th>
                </thead>
                <tbody>
                  <% @pulses.each do |pulse| %>
                  <tr class="table-row" data-href="<%= pulse_path(pulse, patient: params[:patient]) %>">
                    <td>
                      <%= pulse.id %>
                    </td>
                    <td>
                      <%= pulse.created_at %>
                    </td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function($) {
    $(".table-row").click(function() {
        window.document.location = $(this).data("href");
    });
});
</script>

app/views/pulses/show.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
  <div class="container-fluid">
    <div class="navbar-wrapper">
      <a class="navbar-brand">Пульс</a>
    </div>
  </div>
</nav>
<!-- End Navbar -->
<div class="content">
<div id="chartContainer" style="height: 600px;"></div>
<% if is_doctor? %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <form action="<%= pulse_comment_path %>" method="post" >
              <div class="container-fluid">
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label>Комментарий</label>
                      <div class="form-group">
                        <textarea class="form-control" rows="5" name="comment" value="<%= @pulse.comment %>"></textarea>
                        <input type="hidden" name="id" value="<%= @pulse.id %>" />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-primary pull-right">Изменить</button>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <form action="patient" method="post" >
              <div class="container-fluid">
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label>Комментарий</label>
                      <div class="form-group">
                        <%# <label class="bmd-label-floating"> </label> %>
                        <h4><%= @pulse.comment %></h4>
                        <%# <textarea class="form-control" rows="5" value=""></textarea> %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<script>
window.onload = function () {
var array = <%= @array %>;
var new_arr= [];

array.forEach(function(element) {
  new_arr.push({y: element})
});


var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	zoomEnabled: true,
	theme: "light2",
	title:{
		text: "<%= @patient.name %> <%= @patient.last_name %> (<%= @pulse.created_at %>)"
	},
	axisY:{
      	// stripLines:yAxisStripLinesArray,
		includeZero: false,
		gridThickness: 2,
		gridColor:"#DC74A5",
		lineColor:"#DC74A5",
		tickColor:"#DC74A5",
		labelFontColor:"#DC74A5",
	},
	axisX:{
		// stripLines:xAxisStripLinesArray,
		gridThickness: 2,
		gridColor:"#DC74A5",
		lineColor:"#DC74A5",
		tickColor:"#DC74A5",
		labelFontColor:"#DC74A5",
	},
	data: [{
		type: "line",
		color:"black",
		markerSize: 1,
		dataPoints: new_arr
	}]
});
chart.render();

}

</script>

<div id="chartContainer" style="height: 370px; width: 100%;"></div>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>